// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RazorPageMahasiswa.Models;

namespace RazorPageMahasiswa.Migrations
{
    [DbContext(typeof(RazorPageMahasiswaContext))]
    [Migration("20190220075459_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("RazorPageMahasiswa.Models.Mahasiswa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("JenisKelamin");

                    b.Property<string>("Jurusan");

                    b.Property<string>("NPM");

                    b.Property<string>("NamaMahasiswa");

                    b.Property<string>("ProgramStudy");

                    b.Property<DateTime>("TanggalLahir");

                    b.Property<string>("TempatLahir");

                    b.HasKey("ID");

                    b.ToTable("Movie");
                });
#pragma warning restore 612, 618
        }
    }
}
